services:
  notifier:
    container_name: sazka_bonus_calendar_notifier
    image: adamfejtek/sazka_bonus_calendar_notifier
    build: ./
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
    env_file: .env
    volumes:
      - ./data:/app/data
